### PR TITLE
feat(DDB): Add PITR to DynamoDB

### PR DESCRIPTION
**Pull request by vgallissot**
enable PITR to be able to recover unexpected changes or a delete done on this table
Details: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/pointintimerecovery_beforeyoubegin.html

### CODE REVIEW

**Comment by claque2000** [comment]
As dynamodb is only used as lock system to avoid multiple deployments of same stack at the same time, I do not see why PITR can be useful. Terraform will put an entry when deployment start and delete it at the end of deployment.
Do you have any use case where PITR would have been useful on a dynamodb for Terraform lock ?

**Comment by vgallissot** [comment]
You're right, adding PITR is not mandatory. We use it as a possible recover if someone mistakenly removes the table, as PITR comes with an automatic table backup in case of table drop.
It may be useful to add a variable which defaults to false instead, WYT ?

**Review by claque2000 — APPROVED** [review]

**Comment by claque2000** [comment]
Sorry for the insane delay.

**Comment by vgallissot** [comment]
thanks @claque2000 and no worry for the delay :p

**Pull request merged**
